- 👋 Hi, I’m @kouassithierry
- 👀 I’m interested in développement web
- 🌱 I’m currently learning HTML,CSS et JS
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...

<!---
kouassithierry/kouassithierry is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
